name: Vue Front Build and Push

# 1. 이벤트 트리거(on)
on:
    push:
        branches: [main]

# 2. Jobs - runner
jobs:
    build-and-push:
        runs-on: ubuntu-latest #가장 최신의 utuntu runner를 사용
# 3. source checkout
        steps:
        - name: Source Checkout
          uses: actions/checkout@v2
# 4. setup node(백엔드과 다른부분)
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 20.x

# 5. docker build
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v2
# 6. docker login
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}  
            # GitHub Secret에서 Docker Hub 사용자 이름을 가져옵니다.
            password: ${{ secrets.DOCKERHUB_TOKEN }}     
            # GitHub Secret에서 Docker Hub 액세스 토큰을 가져옵니다.
# 7. docker build and push
        - name: Build and Push
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/vueapp:{{ github.sha }}
# 파이프라인 작성이 끝나면 로컬 콘솔에서 이미지 빌드, 실행
# docker build ~~~~~
# docker run port(8080) container_name image